language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
- pip install coveralls requests_mock
script: coverage run --source WazeRouteCalculator -m py.test tests.py -v
after_success:
  coveralls
